// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pls_component_step_cpp
Rcpp::List pls_component_step_cpp(const Rcpp::NumericMatrix& xxwotna_r, const Rcpp::NumericMatrix& xxna_r, const Rcpp::NumericVector& tempww_r, Rcpp::Nullable<Rcpp::NumericMatrix> prev_pp_r, Rcpp::Nullable<Rcpp::NumericMatrix> predict_na_r, const double tol_xi, const bool check_xx, const bool check_predict);
RcppExport SEXP _plsRglm_pls_component_step_cpp(SEXP xxwotna_rSEXP, SEXP xxna_rSEXP, SEXP tempww_rSEXP, SEXP prev_pp_rSEXP, SEXP predict_na_rSEXP, SEXP tol_xiSEXP, SEXP check_xxSEXP, SEXP check_predictSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type xxwotna_r(xxwotna_rSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type xxna_r(xxna_rSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type tempww_r(tempww_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type prev_pp_r(prev_pp_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type predict_na_r(predict_na_rSEXP);
    Rcpp::traits::input_parameter< const double >::type tol_xi(tol_xiSEXP);
    Rcpp::traits::input_parameter< const bool >::type check_xx(check_xxSEXP);
    Rcpp::traits::input_parameter< const bool >::type check_predict(check_predictSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_component_step_cpp(xxwotna_r, xxna_r, tempww_r, prev_pp_r, predict_na_r, tol_xi, check_xx, check_predict));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_plsRglm_pls_component_step_cpp", (DL_FUNC) &_plsRglm_pls_component_step_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_plsRglm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
