# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pls_component_step_cpp <- function(xxwotna_r, xxna_r, tempww_r, prev_pp_r = NULL, predict_na_r = NULL, tol_xi = 1e-12, check_xx = FALSE, check_predict = FALSE) {
    .Call(`_plsRglm_pls_component_step_cpp`, xxwotna_r, xxna_r, tempww_r, prev_pp_r, predict_na_r, tol_xi, check_xx, check_predict)
}

